# .streamlit/secrets.example.toml  (plantilla SIN secretos)

SHEET_URL = "https://docs.google.com/spreadsheets/d/<TU_SHEET_ID>/edit"
SHEET_ID  = "<TU_SHEET_ID>"

# Dónde corre (elige "cloud" o "local")
active = "cloud"
redirect_uris = ["https://eni2025.streamlit.app", "http://localhost:8501"]
javascript_origins = ["https://eni2025.streamlit.app","http://localhost:8501"]

[auth]
# Puedes dejar aquí tus listas si quieres (no son secretos), o moverlas a Secrets también
allowed_emails  = ["tu@correo.com"]
allowed_domains = ["inei.gob.pe","unmsm.edu.pe"]

# Estas secciones DEBEN ir sólo en Secrets reales (no en Git):
# [gcp_service_account]
# [oauth_client]
